### ISSUE TITLE
How can I reproduce the results on VATEX reported in TPAMI?

### ISSUE THREAD

**Issue by ppj567** [danieljf24/hybrid_space#3]
Hi, I am evaluating the model of hybrid_space on VATEX dataset. The reproduced text-to-video results are a bit lower than reported in the paper, which are inferior to HGR model.

![image](https://user-images.githubusercontent.com/78494473/118447068-ed1ffe00-b722-11eb-90f9-37453cba9115.png)
![image](https://user-images.githubusercontent.com/78494473/118447107-f7da9300-b722-11eb-822f-13fb9afc4b53.png)

I tried to retrain the model but cannot reproduce the results superior to HGR. 
Could you give some tips about it? Many thanks.

**Comment by danieljf24** [comment]
Sorry for the late reply.  We used this code, but the performance fluctuates a bit due to random factors in SGD based training.
