### ISSUE TITLE
Search / qwery length

### ISSUE THREAD

**Issue by Tortoise17** [danieljf24/hybrid_space#5]
Without any doubt, this is excellent piece of work.
I want to ask that what is limitation of qwery characters? Is it possible to search long sentence or only limited like CLIP.

so in simple words is it only embedding base or transcript base (sentence base search) search  for video retrieval is also possible. 

Please guide me.

**Comment by danieljf24** [comment]
Sorry for the late reply. As our model was trained on queries of short sentences, it may not work well for queries of long sentences.
